sudo: required
services: docker
rvm:
  - 2.3
before_install:
  - chef --version &> /dev/null || curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 1.4.3
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
install:
  - chef exec bundle install
script:
  - chef exec bundle exec rake full
