name             'greysystems-mongodb'
maintainer       'GreySystems'
maintainer_email 'jmfelguera@greysystems.eu'
license          'BSD-3-Clause'
description      'Installs/Configures greysystems-mongodb'
long_description 'Installs/Configures greysystems-mongodb'
version          '1.4.0'
chef_version '> 12'
supports 'centos'

depends 'mongodb'
depends 'aws'
depends 'selinux'

issues_url 'https://github.com/grey-systems/chef-greysystems-mongodb/issues/new'
source_url 'https://github.com/grey-systems/chef-greysystems-mongodb'
